/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package departmentsystem;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
//import java.awt.Component;
//import javax.swing.JLabel;
//import javax.swing.JOptionPane;
//import javax.swing.JPasswordField;
//import javax.swing.JTextField;

/**
 *
 * @author Askar G
 */
public class ITAssistantUI extends javax.swing.JFrame {
    Color nBlueColor=new Color(41, 54, 63);
    Color orangeColor = new Color (255,165,0);
    Color whiteColor = new Color (255,255,255);
    boolean clicked = false;
    /**
     * Creates new form ITAssistantUI
     */
    ControllerClass c;
    public ITAssistantUI(ControllerClass c) {
        this.c = c;
        setTitle("Local Flex");
        ImageIcon img = new ImageIcon("C:\\Users\\Askar G\\OneDrive\\Documents\\NetBeansProjects\\DepartmentManagementSystem\\src\\images\\f50.png");
        setIconImage(img.getImage());
        initComponents();
        createCourseTab.setVisible(true);
        createStudentsTab.setVisible(false);
        createTeacherTab.setVisible(false);
        studentEnteredLabel.setVisible(false);
        teacherEnteredLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        navbarArea = new javax.swing.JPanel();
        imageArea = new javax.swing.JLabel();
        createCourseLabel = new javax.swing.JLabel();
        addStudentLabel = new javax.swing.JLabel();
        addTeacherLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        createCourseTab = new javax.swing.JPanel();
        teacherNameTextField = new javax.swing.JTextField();
        addCourseButton = new javax.swing.JButton();
        teacherNameLabel = new javax.swing.JLabel();
        courseNameLabel = new javax.swing.JLabel();
        courseNameTextField = new javax.swing.JTextField();
        createStudentsTab = new javax.swing.JPanel();
        studentLastNameLabel = new javax.swing.JLabel();
        studentRollNoTextField = new javax.swing.JTextField();
        studentLastNameTextField = new javax.swing.JTextField();
        studentRollNoLabel = new javax.swing.JLabel();
        studentPasswordLabel = new javax.swing.JLabel();
        studentPasswordTextField = new javax.swing.JTextField();
        studentFirstNameLabel = new javax.swing.JLabel();
        studentFirstNameTextField = new javax.swing.JTextField();
        addStudentButton = new javax.swing.JButton();
        studentEnteredLabel = new javax.swing.JLabel();
        createTeacherTab = new javax.swing.JPanel();
        teacherLastNameLabel = new javax.swing.JLabel();
        teacherLastNameTextField = new javax.swing.JTextField();
        TeacherIdLabel = new javax.swing.JLabel();
        teacherPasswordLabel = new javax.swing.JLabel();
        teacherPasswordTextField = new javax.swing.JTextField();
        teacherFirstNameLabel = new javax.swing.JLabel();
        teacherIdTextField = new javax.swing.JTextField();
        addTeacherButton = new javax.swing.JButton();
        teacherFirstNameTextField = new javax.swing.JTextField();
        teacherEnteredLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navbarArea.setBackground(new java.awt.Color(41, 54, 63));

        imageArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Forange.png"))); // NOI18N
        imageArea.setText("jLabel1");

        createCourseLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        createCourseLabel.setForeground(new java.awt.Color(255, 255, 255));
        createCourseLabel.setText("    create course");
        createCourseLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createCourseLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                createCourseLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                createCourseLabelMouseExited(evt);
            }
        });

        addStudentLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addStudentLabel.setForeground(new java.awt.Color(255, 255, 255));
        addStudentLabel.setText("     add student");
        addStudentLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addStudentLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addStudentLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addStudentLabelMouseExited(evt);
            }
        });

        addTeacherLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addTeacherLabel.setForeground(new java.awt.Color(255, 255, 255));
        addTeacherLabel.setText("     add teacher");
        addTeacherLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addTeacherLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addTeacherLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addTeacherLabelMouseExited(evt);
            }
        });

        logoutButton.setBackground(new java.awt.Color(255, 165, 0));
        logoutButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("logout");
        logoutButton.setBorder(null);
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout navbarAreaLayout = new javax.swing.GroupLayout(navbarArea);
        navbarArea.setLayout(navbarAreaLayout);
        navbarAreaLayout.setHorizontalGroup(
            navbarAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createCourseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addStudentLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addTeacherLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navbarAreaLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(imageArea, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(navbarAreaLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navbarAreaLayout.setVerticalGroup(
            navbarAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarAreaLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(imageArea)
                .addGap(18, 18, 18)
                .addComponent(createCourseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addStudentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addTeacherLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        background.add(navbarArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        createCourseTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        teacherNameTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        teacherNameTextField.setForeground(new java.awt.Color(41, 54, 63));
        teacherNameTextField.setOpaque(false);
        createCourseTab.add(teacherNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 179, 30));

        addCourseButton.setBackground(new java.awt.Color(255, 165, 0));
        addCourseButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addCourseButton.setForeground(new java.awt.Color(255, 255, 255));
        addCourseButton.setText("add course");
        addCourseButton.setBorder(null);
        addCourseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCourseButtonMouseClicked(evt);
            }
        });
        createCourseTab.add(addCourseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 96, 35));

        teacherNameLabel.setBackground(new java.awt.Color(255, 255, 255));
        teacherNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        teacherNameLabel.setForeground(new java.awt.Color(41, 54, 63));
        teacherNameLabel.setText("teacher id");
        createCourseTab.add(teacherNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 146, -1));

        courseNameLabel.setBackground(new java.awt.Color(255, 255, 255));
        courseNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        courseNameLabel.setForeground(new java.awt.Color(41, 54, 63));
        courseNameLabel.setText("course name");
        createCourseTab.add(courseNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 146, -1));

        courseNameTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        courseNameTextField.setForeground(new java.awt.Color(41, 54, 63));
        courseNameTextField.setOpaque(false);
        createCourseTab.add(courseNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 179, 30));

        background.add(createCourseTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 0, 450, 456));

        createStudentsTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studentLastNameLabel.setBackground(new java.awt.Color(255, 255, 255));
        studentLastNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studentLastNameLabel.setForeground(new java.awt.Color(41, 54, 63));
        studentLastNameLabel.setText("Student Last Name");
        createStudentsTab.add(studentLastNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 200, -1));

        studentRollNoTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studentRollNoTextField.setForeground(new java.awt.Color(41, 54, 63));
        studentRollNoTextField.setOpaque(false);
        createStudentsTab.add(studentRollNoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 179, 30));

        studentLastNameTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studentLastNameTextField.setForeground(new java.awt.Color(41, 54, 63));
        studentLastNameTextField.setOpaque(false);
        createStudentsTab.add(studentLastNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 179, 30));

        studentRollNoLabel.setBackground(new java.awt.Color(255, 255, 255));
        studentRollNoLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studentRollNoLabel.setForeground(new java.awt.Color(41, 54, 63));
        studentRollNoLabel.setText("Student Roll Number");
        createStudentsTab.add(studentRollNoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 200, -1));

        studentPasswordLabel.setBackground(new java.awt.Color(255, 255, 255));
        studentPasswordLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studentPasswordLabel.setForeground(new java.awt.Color(41, 54, 63));
        studentPasswordLabel.setText("Student Password");
        createStudentsTab.add(studentPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 200, -1));

        studentPasswordTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studentPasswordTextField.setForeground(new java.awt.Color(41, 54, 63));
        studentPasswordTextField.setOpaque(false);
        createStudentsTab.add(studentPasswordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 179, 30));

        studentFirstNameLabel.setBackground(new java.awt.Color(255, 255, 255));
        studentFirstNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studentFirstNameLabel.setForeground(new java.awt.Color(41, 54, 63));
        studentFirstNameLabel.setText("Student First Name");
        createStudentsTab.add(studentFirstNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 200, -1));

        studentFirstNameTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studentFirstNameTextField.setForeground(new java.awt.Color(41, 54, 63));
        studentFirstNameTextField.setOpaque(false);
        createStudentsTab.add(studentFirstNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 179, 30));

        addStudentButton.setBackground(new java.awt.Color(255, 165, 0));
        addStudentButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addStudentButton.setForeground(new java.awt.Color(255, 255, 255));
        addStudentButton.setText("add student");
        addStudentButton.setBorder(null);
        addStudentButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addStudentButtonMouseClicked(evt);
            }
        });
        createStudentsTab.add(addStudentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 96, 35));

        studentEnteredLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        studentEnteredLabel.setForeground(new java.awt.Color(102, 204, 0));
        studentEnteredLabel.setText("student entered");
        createStudentsTab.add(studentEnteredLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 90, 90));

        background.add(createStudentsTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 440, 450));

        createTeacherTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        teacherLastNameLabel.setBackground(new java.awt.Color(255, 255, 255));
        teacherLastNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        teacherLastNameLabel.setForeground(new java.awt.Color(41, 54, 63));
        teacherLastNameLabel.setText("Teacher Last Name");
        createTeacherTab.add(teacherLastNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 200, -1));

        teacherLastNameTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        teacherLastNameTextField.setForeground(new java.awt.Color(41, 54, 63));
        teacherLastNameTextField.setOpaque(false);
        createTeacherTab.add(teacherLastNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 179, 30));

        TeacherIdLabel.setBackground(new java.awt.Color(255, 255, 255));
        TeacherIdLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TeacherIdLabel.setForeground(new java.awt.Color(41, 54, 63));
        TeacherIdLabel.setText("Teacher ID");
        createTeacherTab.add(TeacherIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 200, -1));

        teacherPasswordLabel.setBackground(new java.awt.Color(255, 255, 255));
        teacherPasswordLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        teacherPasswordLabel.setForeground(new java.awt.Color(41, 54, 63));
        teacherPasswordLabel.setText("Teacher Password");
        createTeacherTab.add(teacherPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 200, -1));

        teacherPasswordTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        teacherPasswordTextField.setForeground(new java.awt.Color(41, 54, 63));
        teacherPasswordTextField.setOpaque(false);
        createTeacherTab.add(teacherPasswordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 179, 30));

        teacherFirstNameLabel.setBackground(new java.awt.Color(255, 255, 255));
        teacherFirstNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        teacherFirstNameLabel.setForeground(new java.awt.Color(41, 54, 63));
        teacherFirstNameLabel.setText("Teacher First Name");
        createTeacherTab.add(teacherFirstNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 200, -1));

        teacherIdTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        teacherIdTextField.setForeground(new java.awt.Color(41, 54, 63));
        teacherIdTextField.setOpaque(false);
        createTeacherTab.add(teacherIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 179, 30));

        addTeacherButton.setBackground(new java.awt.Color(255, 165, 0));
        addTeacherButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addTeacherButton.setForeground(new java.awt.Color(255, 255, 255));
        addTeacherButton.setText("add teacher");
        addTeacherButton.setBorder(null);
        addTeacherButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addTeacherButtonMouseClicked(evt);
            }
        });
        createTeacherTab.add(addTeacherButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 96, 35));

        teacherFirstNameTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        teacherFirstNameTextField.setForeground(new java.awt.Color(41, 54, 63));
        teacherFirstNameTextField.setOpaque(false);
        createTeacherTab.add(teacherFirstNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 179, 30));

        teacherEnteredLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        teacherEnteredLabel.setForeground(new java.awt.Color(102, 204, 0));
        teacherEnteredLabel.setText("teacher entered");
        createTeacherTab.add(teacherEnteredLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 120, -1));

        background.add(createTeacherTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 440, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createCourseLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createCourseLabelMouseEntered
        // TODO add your handling code here:
        if(clicked==false)
        createCourseLabel.setForeground(orangeColor);
    }//GEN-LAST:event_createCourseLabelMouseEntered

    private void createCourseLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createCourseLabelMouseExited
        // TODO add your handling code here:
        if(clicked==false)
        createCourseLabel.setForeground(whiteColor);
    }//GEN-LAST:event_createCourseLabelMouseExited

    private void addStudentLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStudentLabelMouseEntered
        // TODO add your handling code here:
        if(clicked==false)
        addStudentLabel.setForeground(orangeColor);
    }//GEN-LAST:event_addStudentLabelMouseEntered

    private void addStudentLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStudentLabelMouseExited
        // TODO add your handling code here:
        if(clicked==false)
        addStudentLabel.setForeground(whiteColor);
    }//GEN-LAST:event_addStudentLabelMouseExited

    private void addTeacherLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTeacherLabelMouseEntered
        // TODO add your handling code here:
        if(clicked==false)
        addTeacherLabel.setForeground(orangeColor);
    }//GEN-LAST:event_addTeacherLabelMouseEntered

    private void addTeacherLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTeacherLabelMouseExited
        // TODO add your handling code here:
        if(clicked==false)
        addTeacherLabel.setForeground(whiteColor);
    }//GEN-LAST:event_addTeacherLabelMouseExited

    private void createCourseLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createCourseLabelMouseClicked
        // TODO add your handling code here:
        clicked = true;
        studentEnteredLabel.setVisible(false);
        createCourseLabel.setForeground(orangeColor);
        addStudentLabel.setForeground(whiteColor);
        addTeacherLabel.setForeground(whiteColor);
        createCourseTab.setVisible(true);
        createStudentsTab.setVisible(false);
        createTeacherTab.setVisible(false);
    }//GEN-LAST:event_createCourseLabelMouseClicked

    private void addStudentLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStudentLabelMouseClicked
        // TODO add your handling code here:
        clicked = true;
        studentEnteredLabel.setVisible(false);
        createCourseLabel.setForeground(whiteColor);
        addStudentLabel.setForeground(orangeColor);
        addTeacherLabel.setForeground(whiteColor);
        createCourseTab.setVisible(false);
        createStudentsTab.setVisible(true);
        createTeacherTab.setVisible(false);
        studentEnteredLabel.setVisible(false);
    }//GEN-LAST:event_addStudentLabelMouseClicked

    private void addTeacherLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTeacherLabelMouseClicked
        // TODO add your handling code here:
        clicked = true;
        studentEnteredLabel.setVisible(false);
        createCourseLabel.setForeground(whiteColor);
        addStudentLabel.setForeground(whiteColor);
        addTeacherLabel.setForeground(orangeColor);
        createCourseTab.setVisible(false);
        createStudentsTab.setVisible(false);
        createTeacherTab.setVisible(true);
    }//GEN-LAST:event_addTeacherLabelMouseClicked

    private void addStudentButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStudentButtonMouseClicked
        // TODO add your handling code here:
        studentEnteredLabel.setVisible(false);
        String rollNumber = studentRollNoTextField.getText();
        String firstName = studentFirstNameTextField.getText();
        String lastName = studentLastNameTextField.getText();
        String password = studentPasswordTextField.getText();
        if(!c.addStudent(rollNumber, firstName, lastName, password))
            JOptionPane.showMessageDialog(this,"student with this id already exists!");
        else{
            studentEnteredLabel.setVisible(true);
        studentRollNoTextField.setText("");
        studentFirstNameTextField.setText("");
        studentLastNameTextField.setText("");
        studentPasswordTextField.setText("");}
        c.displayStudents();
    }//GEN-LAST:event_addStudentButtonMouseClicked

    private void addTeacherButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTeacherButtonMouseClicked
        // TODO add your handling code here:
        teacherEnteredLabel.setVisible(false);
        String id = teacherIdTextField.getText();
        String firstName = teacherFirstNameTextField.getText();
        String lastName = teacherLastNameTextField.getText();
        String password = teacherPasswordTextField.getText();
        if(!c.addTeacher(id,firstName, lastName, password))
            JOptionPane.showMessageDialog(this,"teacher with this id already exists!");
        else{
            teacherEnteredLabel.setVisible(true);
        teacherIdTextField.setText("");
        teacherFirstNameTextField.setText("");
        teacherLastNameTextField.setText("");
        teacherPasswordTextField.setText("");}
        c.displayTeachers();
    }//GEN-LAST:event_addTeacherButtonMouseClicked

    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        // TODO add your handling code here:
        c.saveStudents();
        c.saveTeachers();
        c.saveCourses();
        c.saveBooks();
        c.saveRegistrations();
        setVisible(false);
        loginGui l = new loginGui(c);
    }//GEN-LAST:event_logoutButtonMouseClicked

    private void addCourseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCourseButtonMouseClicked
        // TODO add your handling code here:
        String courseName = courseNameTextField.getText();
        String teacherName = teacherNameTextField.getText();
        if(!c.addCourse(courseName, teacherName))
            JOptionPane.showMessageDialog(this,"not entered!");
        else
        {
            courseNameTextField.setText("");
            teacherNameTextField.setText("");
            JOptionPane.showMessageDialog(this,"entered!");
        }
    }//GEN-LAST:event_addCourseButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ITAssistantUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ITAssistantUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ITAssistantUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ITAssistantUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        ControllerClass c = new ControllerClass();
        new ITAssistantUI(c).setVisible(true);
        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ITAssistantUI().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TeacherIdLabel;
    private javax.swing.JButton addCourseButton;
    private javax.swing.JButton addStudentButton;
    private javax.swing.JLabel addStudentLabel;
    private javax.swing.JButton addTeacherButton;
    private javax.swing.JLabel addTeacherLabel;
    private javax.swing.JPanel background;
    private javax.swing.JLabel courseNameLabel;
    private javax.swing.JTextField courseNameTextField;
    private javax.swing.JLabel createCourseLabel;
    private javax.swing.JPanel createCourseTab;
    private javax.swing.JPanel createStudentsTab;
    private javax.swing.JPanel createTeacherTab;
    private javax.swing.JLabel imageArea;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel navbarArea;
    private javax.swing.JLabel studentEnteredLabel;
    private javax.swing.JLabel studentFirstNameLabel;
    private javax.swing.JTextField studentFirstNameTextField;
    private javax.swing.JLabel studentLastNameLabel;
    private javax.swing.JTextField studentLastNameTextField;
    private javax.swing.JLabel studentPasswordLabel;
    private javax.swing.JTextField studentPasswordTextField;
    private javax.swing.JLabel studentRollNoLabel;
    private javax.swing.JTextField studentRollNoTextField;
    private javax.swing.JLabel teacherEnteredLabel;
    private javax.swing.JLabel teacherFirstNameLabel;
    private javax.swing.JTextField teacherFirstNameTextField;
    private javax.swing.JTextField teacherIdTextField;
    private javax.swing.JLabel teacherLastNameLabel;
    private javax.swing.JTextField teacherLastNameTextField;
    private javax.swing.JLabel teacherNameLabel;
    private javax.swing.JTextField teacherNameTextField;
    private javax.swing.JLabel teacherPasswordLabel;
    private javax.swing.JTextField teacherPasswordTextField;
    // End of variables declaration//GEN-END:variables
}
