/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package departmentsystem;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Askar G
 */
public class StudentUI extends javax.swing.JFrame {
    Color nBlueColor = new Color(41, 54, 63);
    Color orangeColor = new Color (255,165,0);
    Color whiteColor = new Color (255,255,255);
    boolean clicked = false;
    boolean bookSearched=false;
    JScrollPane aPane = new JScrollPane();
    JScrollPane ePane = new JScrollPane();
    /**
     * Creates new form StudentUI
     */
    ControllerClass c;
    Student s;
    String[] coursesNames;
    public StudentUI(ControllerClass cl,Student std) {
        c=cl;
       s=std;
        initComponents();
        loadCoursesOnTable();
        loadCoursesRegisteredOnAttendance();
        loadCoursesRegisteredOnEvaluation();
        registrationTab.setVisible(true);
        addBookTab.setVisible(false);
        lendBookTab.setVisible(false);
        viewAttendanceTab.setVisible(false);
        ImageIcon img = new ImageIcon("C:\\Users\\Askar G\\OneDrive\\Documents\\NetBeansProjects\\DepartmentManagementSystem\\src\\images\\f50.png");
        setIconImage(img.getImage());
        setTitle("Local flex");
        if(s.noOfRegistrations()!=0)
        loadDatesOnTable(coursesNames[0]);
        if(s.noOfRegistrations()!=0)
        loadEvaluationsOnTable(coursesNames[0]);
        attendanceTable.add(aPane);
        courseEvaluationTable.add(ePane);
    }
    
    public void loadDatesOnTable(String courseName)
    {   
        attendanceTable.removeAll();
        ArrayList<String> dates = s.getDates(courseName);
        ArrayList<String> status = s.getStatus(courseName);
        DefaultTableModel m= new DefaultTableModel();
        m.addColumn(new String("Date"));
        m.addColumn(new String("P/A"));
        attendanceTable.setModel(m);
        for(int i=0;i<dates.size();i++)
        {
            m.addRow(new Object[]{dates.get(i),status.get(i)});
        }
    }
    
    public void loadEvaluationsOnTable(String courseName)
    {   
        courseEvaluationTable.removeAll();
        ArrayList<String> evaluations = s.getEvaluations(courseName);
        ArrayList<String> marks = s.getMarks(courseName);
        DefaultTableModel m= new DefaultTableModel();
        m.addColumn(new String("Evaluation"));
        m.addColumn(new String("Marks"));
        courseEvaluationTable.setModel(m);
        for(int i=0;i<evaluations.size();i++)
        {
            m.addRow(new Object[]{evaluations.get(i),marks.get(i)});
        }
    }
    
    public void loadCoursesRegisteredOnAttendance()
    {
        coursesNames = s.getRegisteredCourses();
        for(int i=0;i<s.noOfRegistrations();i++)
        {
            coursesRegisteredComboBox.addItem(coursesNames[i]);
        }
        
    }
    
    public void loadCoursesRegisteredOnEvaluation()
    {
        coursesNames = s.getRegisteredCourses();
        for(int i=0;i<s.noOfRegistrations();i++)
        {
            courseEvaluatedComboBox.addItem(coursesNames[i]);
        }
        
    }
    
    public void loadCoursesOnTable()
    {
        String [] courseList = c.getAllCourses();
        DefaultListModel m = new DefaultListModel();
        for(int i=0;i<courseList.length;i++)
        {
            //System.out.println(courseList[i]);
            m.addElement(courseList[i]);
        }
        registrationCourses.setModel(m);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backGround = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        attendanceLabel = new javax.swing.JLabel();
        marksLabel = new javax.swing.JLabel();
        register = new javax.swing.JLabel();
        lendBookLabel = new javax.swing.JLabel();
        addBookLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        addBookTab = new javax.swing.JPanel();
        bookNameTextField = new javax.swing.JTextField();
        bookDetailsLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bookDetailsTextArea = new javax.swing.JTextArea();
        bookNameLabel = new javax.swing.JLabel();
        addBookButton = new javax.swing.JButton();
        registrationTab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        registrationCourses = new javax.swing.JList<>();
        registerCourse1 = new javax.swing.JButton();
        lendBookTab = new javax.swing.JPanel();
        searchBookNameTextField = new javax.swing.JTextField();
        searchBookNameLabel = new javax.swing.JLabel();
        lendBookButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        searchBookResults = new javax.swing.JTextArea();
        searchBookButton = new javax.swing.JButton();
        viewAttendanceTab = new javax.swing.JPanel();
        coursesRegisteredComboBox = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        attendanceTable = new javax.swing.JTable();
        evaluationTab = new javax.swing.JPanel();
        courseEvaluatedComboBox = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        courseEvaluationTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(41, 54, 63));

        attendanceLabel.setBackground(new java.awt.Color(41, 54, 63));
        attendanceLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        attendanceLabel.setForeground(new java.awt.Color(255, 255, 255));
        attendanceLabel.setText("       attendance");
        attendanceLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attendanceLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                attendanceLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                attendanceLabelMouseExited(evt);
            }
        });

        marksLabel.setBackground(new java.awt.Color(41, 54, 63));
        marksLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        marksLabel.setForeground(new java.awt.Color(255, 255, 255));
        marksLabel.setText("          marks");
        marksLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                marksLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                marksLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                marksLabelMouseExited(evt);
            }
        });

        register.setBackground(new java.awt.Color(41, 54, 63));
        register.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        register.setForeground(new java.awt.Color(255, 255, 255));
        register.setText("         register");
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerMouseExited(evt);
            }
        });

        lendBookLabel.setBackground(new java.awt.Color(41, 54, 63));
        lendBookLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lendBookLabel.setForeground(new java.awt.Color(255, 255, 255));
        lendBookLabel.setText("        lend book");
        lendBookLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lendBookLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lendBookLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lendBookLabelMouseExited(evt);
            }
        });

        addBookLabel.setBackground(new java.awt.Color(41, 54, 63));
        addBookLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addBookLabel.setForeground(new java.awt.Color(255, 255, 255));
        addBookLabel.setText("        add book");
        addBookLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBookLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addBookLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addBookLabelMouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Forange.png"))); // NOI18N

        logoutButton.setBackground(new java.awt.Color(255, 165, 0));
        logoutButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("logout");
        logoutButton.setBorder(null);
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(attendanceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(marksLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lendBookLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addBookLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addComponent(register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addGap(78, 78, 78)
                .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(marksLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(attendanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lendBookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addBookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        backGround.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        addBookTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookNameTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bookNameTextField.setForeground(new java.awt.Color(41, 54, 63));
        bookNameTextField.setOpaque(false);
        addBookTab.add(bookNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 179, 30));

        bookDetailsLabel.setBackground(new java.awt.Color(255, 255, 255));
        bookDetailsLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bookDetailsLabel.setForeground(new java.awt.Color(41, 54, 63));
        bookDetailsLabel.setText("book address");
        addBookTab.add(bookDetailsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 146, -1));

        bookDetailsTextArea.setColumns(20);
        bookDetailsTextArea.setRows(5);
        jScrollPane2.setViewportView(bookDetailsTextArea);

        addBookTab.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        bookNameLabel.setBackground(new java.awt.Color(255, 255, 255));
        bookNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bookNameLabel.setForeground(new java.awt.Color(41, 54, 63));
        bookNameLabel.setText("Book name");
        addBookTab.add(bookNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 146, -1));

        addBookButton.setBackground(new java.awt.Color(255, 165, 0));
        addBookButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addBookButton.setForeground(new java.awt.Color(255, 255, 255));
        addBookButton.setText("add book");
        addBookButton.setBorder(null);
        addBookButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBookButtonMouseClicked(evt);
            }
        });
        addBookTab.add(addBookButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 110, 35));

        backGround.add(addBookTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 480, 600));

        registrationTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registrationCourses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrationCoursesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(registrationCourses);

        registrationTab.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 110, -1));

        registerCourse1.setBackground(new java.awt.Color(255, 165, 0));
        registerCourse1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        registerCourse1.setForeground(new java.awt.Color(255, 255, 255));
        registerCourse1.setText("register course");
        registerCourse1.setBorder(null);
        registerCourse1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerCourse1MouseClicked(evt);
            }
        });
        registrationTab.add(registerCourse1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 110, 35));

        backGround.add(registrationTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 470, 600));

        lendBookTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchBookNameTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchBookNameTextField.setForeground(new java.awt.Color(41, 54, 63));
        searchBookNameTextField.setOpaque(false);
        lendBookTab.add(searchBookNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 179, 30));

        searchBookNameLabel.setBackground(new java.awt.Color(255, 255, 255));
        searchBookNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchBookNameLabel.setForeground(new java.awt.Color(41, 54, 63));
        searchBookNameLabel.setText("Book name");
        lendBookTab.add(searchBookNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 146, -1));

        lendBookButton.setBackground(new java.awt.Color(255, 165, 0));
        lendBookButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lendBookButton.setForeground(new java.awt.Color(255, 255, 255));
        lendBookButton.setText("lend book");
        lendBookButton.setBorder(null);
        lendBookButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lendBookButtonMouseClicked(evt);
            }
        });
        lendBookTab.add(lendBookButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 90, 30));

        searchBookResults.setColumns(20);
        searchBookResults.setRows(5);
        searchBookResults.setText("no search results");
        jScrollPane3.setViewportView(searchBookResults);

        lendBookTab.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 180, 150));

        searchBookButton.setBackground(new java.awt.Color(255, 165, 0));
        searchBookButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchBookButton.setForeground(new java.awt.Color(255, 255, 255));
        searchBookButton.setText("search");
        searchBookButton.setBorder(null);
        searchBookButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBookButtonMouseClicked(evt);
            }
        });
        lendBookTab.add(searchBookButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 90, 30));

        backGround.add(lendBookTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 470, 600));

        viewAttendanceTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        coursesRegisteredComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                coursesRegisteredComboBoxItemStateChanged(evt);
            }
        });
        coursesRegisteredComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                coursesRegisteredComboBoxMouseClicked(evt);
            }
        });
        viewAttendanceTab.add(coursesRegisteredComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 70, -1));

        attendanceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "P/A"
            }
        ));
        jScrollPane4.setViewportView(attendanceTable);

        viewAttendanceTab.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 450, 320));

        backGround.add(viewAttendanceTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 470, 600));

        evaluationTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        courseEvaluatedComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                courseEvaluatedComboBoxItemStateChanged(evt);
            }
        });
        courseEvaluatedComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                courseEvaluatedComboBoxMouseClicked(evt);
            }
        });
        evaluationTab.add(courseEvaluatedComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 70, -1));

        courseEvaluationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Evaluation", "marks"
            }
        ));
        jScrollPane5.setViewportView(courseEvaluationTable);

        evaluationTab.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 450, 330));

        backGround.add(evaluationTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 470, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void attendanceLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendanceLabelMouseEntered
        // TODO add your handling code here:
        if(clicked==false)
        attendanceLabel.setForeground(orangeColor);
    }//GEN-LAST:event_attendanceLabelMouseEntered

    private void attendanceLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendanceLabelMouseExited
        // TODO add your handling code here:
        if(clicked==false)
        attendanceLabel.setForeground(whiteColor);
    }//GEN-LAST:event_attendanceLabelMouseExited

    private void marksLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marksLabelMouseEntered
        // TODO add your handling code here:
        if(clicked==false)
        marksLabel.setForeground(orangeColor);
    }//GEN-LAST:event_marksLabelMouseEntered

    private void marksLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marksLabelMouseExited
        // TODO add your handling code here:
        if(clicked==false)
        marksLabel.setForeground(whiteColor);
    }//GEN-LAST:event_marksLabelMouseExited

    private void registerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseEntered
        // TODO add your handling code here:
        if(clicked==false)
        register.setForeground(orangeColor);
    }//GEN-LAST:event_registerMouseEntered

    private void registerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseExited
        // TODO add your handling code here:
        if(clicked==false)
        register.setForeground(whiteColor);
    }//GEN-LAST:event_registerMouseExited

    private void lendBookLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lendBookLabelMouseEntered
        // TODO add your handling code here:
        if(clicked==false)
        lendBookLabel.setForeground(orangeColor);
    }//GEN-LAST:event_lendBookLabelMouseEntered

    private void lendBookLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lendBookLabelMouseExited
        // TODO add your handling code here:
        if(clicked==false)
        lendBookLabel.setForeground(whiteColor);
    }//GEN-LAST:event_lendBookLabelMouseExited

    private void addBookLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBookLabelMouseEntered
        // TODO add your handling code here:
        if(clicked==false)
        addBookLabel.setForeground(orangeColor);
    }//GEN-LAST:event_addBookLabelMouseEntered

    private void addBookLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBookLabelMouseExited
        // TODO add your handling code here:
        if(clicked==false)
        addBookLabel.setForeground(whiteColor);
    }//GEN-LAST:event_addBookLabelMouseExited

    private void registrationCoursesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrationCoursesMouseClicked

    }//GEN-LAST:event_registrationCoursesMouseClicked

    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        // TODO add your handling code here:
        c.saveCourses();
        c.saveTeachers();
        c.saveStudents();
        c.saveRegistrations();
        c.saveBooks();
        c.saveStudentsAttendance();
        c.saveStudentsEvaluations();
        setVisible(false);
        new loginGui(c);
    }//GEN-LAST:event_logoutButtonMouseClicked

    private void registerCourse1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerCourse1MouseClicked
        // TODO add your handling code here:
        String courseName = registrationCourses.getSelectedValue().toString();
        System.out.println(s.getLastName());
        if(c.registerCourses(courseName, s))
            JOptionPane.showMessageDialog(this,"Congratulations! You have registered!");
        else
            JOptionPane.showMessageDialog(this,"You have already registered!");
        bookSearched=false;
    }//GEN-LAST:event_registerCourse1MouseClicked

    private void addBookLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBookLabelMouseClicked
        // TODO add your handling code here:
        clicked=true;
        registrationTab.setVisible(false);
        addBookTab.setVisible(true);
        lendBookTab.setVisible(false);
        viewAttendanceTab.setVisible(false);
        marksLabel.setForeground(whiteColor);
        register.setForeground(whiteColor);
        attendanceLabel.setForeground(whiteColor);
        lendBookLabel.setForeground(whiteColor);
        addBookLabel.setForeground(orangeColor);
        evaluationTab.setVisible(false);
    }//GEN-LAST:event_addBookLabelMouseClicked

    private void registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseClicked
        // TODO add your handling code here:
        clicked=true;
        registrationTab.setVisible(true);
        addBookTab.setVisible(false);
        lendBookTab.setVisible(false);
        marksLabel.setForeground(whiteColor);
        register.setForeground(orangeColor);
        attendanceLabel.setForeground(whiteColor);
        lendBookLabel.setForeground(whiteColor);
        addBookLabel.setForeground(whiteColor);
        viewAttendanceTab.setVisible(false);
        evaluationTab.setVisible(false);
    }//GEN-LAST:event_registerMouseClicked

    private void addBookButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBookButtonMouseClicked
        // TODO add your handling code here:
        String name = bookNameTextField.getText();
        String note = bookDetailsTextArea.getText();
        System.out.println(note);
        if(!name.equals("") && !note.equals(""))
        {
            c.addBook(name, note);
            JOptionPane.showMessageDialog(this,"Thank you for helping other students!");
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Please enter the name and address correctly!");
        }
    }//GEN-LAST:event_addBookButtonMouseClicked

    private void lendBookButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lendBookButtonMouseClicked
        // TODO add your handling code here:
        String bookName = searchBookNameTextField.getText();
            String address = c.searchBook(bookName);
            if(address!=null)
            {
                bookSearched =true;
                c.lendBook(bookName);
                JOptionPane.showMessageDialog(this,"Address is "+address);
            }
            else
            {
                bookSearched=false;
                JOptionPane.showMessageDialog(this,"not available");
            }
    }//GEN-LAST:event_lendBookButtonMouseClicked

    private void searchBookButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBookButtonMouseClicked
        // TODO add your handling code here:
        String bookName = searchBookNameTextField.getText();
        String address = c.searchBook(bookName);
        if(address!=null)
        {
            bookSearched =true;
            searchBookResults.setText(bookName + "\n" + address);
        }
        else
        {
            bookSearched=false;
            searchBookResults.setText("No results available");
        }
    }//GEN-LAST:event_searchBookButtonMouseClicked

    private void lendBookLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lendBookLabelMouseClicked
        // TODO add your handling code here:
        clicked=true;
        registrationTab.setVisible(false);
        addBookTab.setVisible(false);
        lendBookTab.setVisible(true);
        viewAttendanceTab.setVisible(false);
        marksLabel.setForeground(whiteColor);
        register.setForeground(whiteColor);
        attendanceLabel.setForeground(whiteColor);
        lendBookLabel.setForeground(orangeColor);
        addBookLabel.setForeground(whiteColor);
        evaluationTab.setVisible(false);
    }//GEN-LAST:event_lendBookLabelMouseClicked

    private void attendanceLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendanceLabelMouseClicked
        // TODO add your handling code here:
        clicked=true;
        registrationTab.setVisible(false);
        addBookTab.setVisible(false);
        lendBookTab.setVisible(false);
        viewAttendanceTab.setVisible(true);
        marksLabel.setForeground(whiteColor);
        register.setForeground(whiteColor);
        attendanceLabel.setForeground(orangeColor);
        lendBookLabel.setForeground(whiteColor);
        addBookLabel.setForeground(whiteColor);
        evaluationTab.setVisible(false);
    }//GEN-LAST:event_attendanceLabelMouseClicked

    private void coursesRegisteredComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coursesRegisteredComboBoxMouseClicked
        // TODO add your handling code here:
        loadDatesOnTable(coursesRegisteredComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_coursesRegisteredComboBoxMouseClicked

    private void coursesRegisteredComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_coursesRegisteredComboBoxItemStateChanged
        // TODO add your handling code here:
        loadDatesOnTable(coursesRegisteredComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_coursesRegisteredComboBoxItemStateChanged

    private void courseEvaluatedComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_courseEvaluatedComboBoxItemStateChanged
        // TODO add your handling code here:
        loadEvaluationsOnTable(courseEvaluatedComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_courseEvaluatedComboBoxItemStateChanged

    private void courseEvaluatedComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courseEvaluatedComboBoxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_courseEvaluatedComboBoxMouseClicked

    private void marksLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marksLabelMouseClicked
        // TODO add your handling code here:
        evaluationTab.setVisible(true);
        clicked=true;
        registrationTab.setVisible(false);
        addBookTab.setVisible(false);
        lendBookTab.setVisible(false);
        viewAttendanceTab.setVisible(false);
        marksLabel.setForeground(orangeColor);
        register.setForeground(whiteColor);
        attendanceLabel.setForeground(whiteColor);
        lendBookLabel.setForeground(whiteColor);
        addBookLabel.setForeground(whiteColor);
    }//GEN-LAST:event_marksLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new StudentUI().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBookButton;
    private javax.swing.JLabel addBookLabel;
    private javax.swing.JPanel addBookTab;
    private javax.swing.JLabel attendanceLabel;
    private javax.swing.JTable attendanceTable;
    private javax.swing.JPanel backGround;
    private javax.swing.JLabel bookDetailsLabel;
    private javax.swing.JTextArea bookDetailsTextArea;
    private javax.swing.JLabel bookNameLabel;
    private javax.swing.JTextField bookNameTextField;
    private javax.swing.JComboBox<String> courseEvaluatedComboBox;
    private javax.swing.JTable courseEvaluationTable;
    private javax.swing.JComboBox<String> coursesRegisteredComboBox;
    private javax.swing.JPanel evaluationTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton lendBookButton;
    private javax.swing.JLabel lendBookLabel;
    private javax.swing.JPanel lendBookTab;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel marksLabel;
    private javax.swing.JLabel register;
    private javax.swing.JButton registerCourse1;
    private javax.swing.JList<String> registrationCourses;
    private javax.swing.JPanel registrationTab;
    private javax.swing.JButton searchBookButton;
    private javax.swing.JLabel searchBookNameLabel;
    private javax.swing.JTextField searchBookNameTextField;
    private javax.swing.JTextArea searchBookResults;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel viewAttendanceTab;
    // End of variables declaration//GEN-END:variables
}
